### ISSUE TITLE
travel: Add simple search for next connection.

### ISSUE THREAD

**Issue by pepol** [mrshu/brutal-plugins#105]
Sometimes, when trying to find a connection between points A and B, you want to be extra sure and know of more options within some time interval. Currently, to achieve this, you need to make request for every connection, changing the starting time.

It would be ideal to have a command such as: `!vlak next`, which would take user's (or in general) last connection and find the next one with the same source and destination.

@Adman could you take a look into this?

**Comment by pepol** [comment]
Cc: @mrshu

**Comment by Adman** [comment]
Done.
