### ISSUE TITLE
Sticky notes for nicks

### ISSUE THREAD

**Issue by mrshu** [mrshu/brutal-plugins#42]
It so happens that many people either just join a channel for a while and then leave without others being able to contact them in such a small time window or they just change their nicks and become unavailable again to the same effect.

It would be great to have a command that would let a user leave a sticky note for someone which would be sent to this person on join/nickchange.

**Comment by mrshu** [comment]
@Adman is there any reason for closing this? We should close issues once they are fully resolved which I do not think is the situation here.

**Comment by Adman** [comment]
@mrshu Uh, sorry, I thought it's already been resolved.

**Comment by mrshu** [comment]
@Adman @pepol ok, well, I'd say it's pretty much resolved now.
