### ISSUE TITLE
Consolidate docstrings quotation marks in basic.py

### ISSUE THREAD

**Issue by mrshu** [mrshu/brutal-plugins#78]
In `basic.py` there are now two types of quotation marks for docstrings: `'''` and `"""`. It is prefered to use `"""` wherever possible and thus the docstrings in this file should also use just these quotation marks.

**Comment by JakubNvk** [comment]
@mrshu I took a look at the `basic.py` and I don't really see any `'''` quotation mars.

**Comment by mrshu** [comment]
@JakubNvk thanks a ton for doing this!
