### ISSUE TITLE
top_karma: Add option to list top N nicks with most karma points

### ISSUE THREAD

**Issue by mrshu** [mrshu/brutal-plugins#82]
Currently, `top_karma` only lists the top 5 nicks with most karma points.

It would be nice to be able to provide an optional numeric parameter to `top_karma` which would let us list the top N nicks with most karma points.

**Comment by mrshu** [comment]
@JakubNvk would you look into this?

**Comment by JakubNvk** [comment]
@mrshu sure.

**Comment by mrshu** [comment]
Should be done in #84. Closing.
